az pipeline refactoring

diff --git a/.azure-pipelines/templates/codecov.yaml b/.azure-pipelines/templates/codecov.yaml
--- a/.azure-pipelines/templates/codecov.yaml
+++ b/.azure-pipelines/templates/codecov.yaml
@@ -3,8 +3,6 @@ parameters:
   type: string
 - name: vmssName
   type: string
-- name: sshKeySecureFile
-  type: string
 - name: platform
   type: string
   default: 'cuda'
@@ -12,57 +10,17 @@ parameters:
   type: string
 
 steps:
-- task: Bash@3
-  name: BuildCoverage
-  displayName: Build with coverage
-  inputs:
-    targetType: 'inline'
-    script: |
-      mkdir build && cd build
-      if [ "${{ parameters.platform }}" == "rocm" ]; then
-        CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_BUILD_TYPE=Debug -DMSCCLPP_BYPASS_GPU_CHECK=ON -DMSCCLPP_USE_ROCM=ON -DMSCCLPP_BUILD_TESTS=ON -DMSCCLPP_GPU_ARCHS=${{ parameters.gpuArch }} -DMSCCLPP_ENABLE_COVERAGE=ON ..
-      else
-        cmake -DCMAKE_BUILD_TYPE=Debug -DMSCCLPP_BYPASS_GPU_CHECK=ON -DMSCCLPP_USE_CUDA=ON -DMSCCLPP_BUILD_TESTS=ON -DMSCCLPP_GPU_ARCHS=${{ parameters.gpuArch }} -DMSCCLPP_ENABLE_COVERAGE=ON ..
-      fi
-      make -j
-      cd ..
-      pwd > build/BUILD_PREFIX
-    workingDirectory: '$(System.DefaultWorkingDirectory)'
-
-- task: DownloadSecureFile@1
-  name: SshKeyFile
-  displayName: Download key file
-  inputs:
-    secureFile: ${{ parameters.sshKeySecureFile }}
-
-- task: Bash@3
-  name: InstallPackages
-  displayName: Install Packages
-  inputs:
-    targetType: 'inline'
-    script: |
-      sudo apt-get update -y
-      sudo apt-get install pssh -y
-      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-
-- task: AzureCLI@2
-  name: StartVMSS
-  displayName: Start VMSS
-  inputs:
-    azureSubscription: ${{ parameters.subscription }}
-    scriptType: bash
-    scriptLocation: inlineScript
-    inlineScript: |
-      az vmss start --name ${{ parameters.vmssName }}  --resource-group mscclpp
-
-- task: Bash@3
-  name: DeployTestEnv
-  displayName: Deploy Test Env
-  inputs:
-    targetType: filePath
-    filePath: test/deploy/deploy.sh
-    arguments: "single-node-test true ${{ parameters.platform }}"
-    workingDirectory: '$(System.DefaultWorkingDirectory)'
+- template: templates/deploy.yaml
+  parameters:
+    subscription:     ${{ parameters.subscription }}
+    vmssName:         ${{ parameters.vmssName }}
+    platform:         ${{ parameters.platform }}
+    gpuArch:          ${{ parameters.gpuArch }}
+    buildType:        Debug
+    cmakeArgs:        '-DMSCCLPP_ENABLE_COVERAGE=ON'
+    buildDisplayName: 'Build with coverage'
+    buildName:        BuildCoverage
+    deployArgs:       'single-node-test true ${{ parameters.platform }}'
 
 - task: Bash@3
   name: TestsCoverageNonPerf
@@ -70,30 +28,26 @@ steps:
   inputs:
     targetType: 'inline'
     script: |
-      set -e
-      HOSTFILE=$(System.DefaultWorkingDirectory)/test/deploy/hostfile_ci
-      SSH_OPTION="StrictHostKeyChecking=no"
-      KeyFilePath=${SSHKEYFILE_SECUREFILEPATH}
-      : > azureuser@10.0.0.4
-      tail -f azureuser@10.0.0.4 &
-      CHILD_PID=$!
-      parallel-ssh -t 0 -h ${HOSTFILE} -x "-i ${KeyFilePath}" -o .    \
-        -O $SSH_OPTION 'sudo docker exec -t mscclpp-test bash -c "    \
-        export PATH=/usr/local/mpi/bin:\$PATH;                        \
-        cd /root/mscclpp;                                             \
-        BUILD_PREFIX=\$(cat build/BUILD_PREFIX);                    \
-        STRIP_COUNT=\$(echo \$BUILD_PREFIX | tr -cd / | wc -c);      \
-        export GCOV_PREFIX=/root/mscclpp;                             \
-        export GCOV_PREFIX_STRIP=\$STRIP_COUNT;                      \
-        export LD_LIBRARY_PATH=/root/mscclpp/build/lib:\$LD_LIBRARY_PATH; \
-        ./build/bin/unit_tests;                                       \
-        mpirun --allow-run-as-root -tag-output -np 2 ./build/bin/mp_unit_tests --exclude-perf-tests;  \
-        mpirun --allow-run-as-root -tag-output -np 4 ./build/bin/mp_unit_tests --exclude-perf-tests;  \
-        cd build;                                                     \
-        lcov --directory . --capture --output-file coverage.info --ignore-errors inconsistent;  \
-        lcov --extract coverage.info \"\${BUILD_PREFIX}/src/*\" \"\${BUILD_PREFIX}/include/mscclpp/*\" --output-file coverage.info;  \
-        lcov --list coverage.info"'
-      kill $CHILD_PID
+      test/deploy/run-remote.sh '\
+        BUILD_PREFIX=\$(cat build/BUILD_PREFIX); \
+        STRIP_COUNT=\$(echo \$BUILD_PREFIX | tr -cd / | wc -c); \
+        export GCOV_PREFIX=/root/mscclpp; \
+        export GCOV_PREFIX_STRIP=\$STRIP_COUNT; \
+        ./build/bin/unit_tests; \
+        mpirun --allow-run-as-root -tag-output -np 2 ./build/bin/mp_unit_tests --exclude-perf-tests; \
+        mpirun --allow-run-as-root -tag-output -np 4 ./build/bin/mp_unit_tests --exclude-perf-tests; \
+        lcov --version; \
+        LCOV_CAPTURE_ARGS=""; \
+        if lcov --help 2>&1 | grep -q "inconsistent"; then \
+          LCOV_CAPTURE_ARGS="--ignore-errors inconsistent"; \
+        fi; \
+        lcov --directory . --capture --output-file coverage.info ${LCOV_CAPTURE_ARGS}; \
+        if [ ! -s coverage.info ]; then \
+          echo "ERROR: coverage.info was not generated. Tests may have failed before coverage capture or produced no gcov data."; \
+          exit 1; \
+        fi; \
+        lcov --extract coverage.info "\${BUILD_PREFIX}/src/*" "\${BUILD_PREFIX}/include/mscclpp/*" --output-file coverage.info; \
+        lcov --list coverage.info'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
 
 - task: Bash@3
@@ -124,13 +78,7 @@ steps:
       ./codecov upload-process --disable-search -t $(CODECOV_TOKEN) -f coverage.info --flag ${{ parameters.platform }}-${{ parameters.gpuArch }}
     workingDirectory: '$(System.DefaultWorkingDirectory)'
 
-- task: AzureCLI@2
-  name: StopVMSS
-  displayName: Deallocate VMSS
-  condition: always()
-  inputs:
-    azureSubscription: ${{ parameters.subscription }}
-    scriptType: bash
-    scriptLocation: inlineScript
-    inlineScript: |
-      az vmss deallocate --name ${{ parameters.vmssName }} --resource-group mscclpp
+- template: templates/stop.yaml
+  parameters:
+    subscription: ${{ parameters.subscription }}
+    vmssName:     ${{ parameters.vmssName }}
